input:
  config: null
  r1: null
  r2: null
  tags: null
  csv: ../marbel_datasets/sim_reads_200.csv
  cached_reads: null
  cached_graph: null
  gene_summary: null
stranded: false
strand_dir: fr
out: ../rust-debruijn/test_data/test_graph_ids
checkpoint: true
format: bin
kmer: kmer16
summarizer: id-sum
min: 1
filter_group_frac: none
group_frac: 0.3333
filter_p: null
stat_test: welchs-t-test
filter_graph: false
filter_component_length: null
filter_component_group_frac: none
component_group_frac: null
filter_component_p: null
keep_unpaired_reads: false
read_name_end: false
time: false
progress: false
memory: 10
threads: 1
strictness: skip
paths: false
stats: false
sample_comp_size: 200
significant_p: 0.05
color_by: fold-change
kill: false
uncompressed: false
mute: false
prune: false
