name: Docs
on: 
  push:
    branches: [main, feat/gh-pages-docs]
permissions: 
  contents: read
  pages: write
  id-token: write
jobs: 
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: clean docs folder
        run: cargo clean --doc
      - name: build docs
        run: cargo doc --no-deps
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with: 
          path: target/doc/debruijn
  deploy: 
    name: deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v4