name: Run tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release
      - name: build rust tests
        run: cargo test --release --no-run
      - name: run rust tests
        run: cargo test -- -test-threads=1
